name: log-and-database

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn
      - run: yarn test
